name: racingla-dev


services:
  db:
    image: mongo
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=racingla
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/racingla --quiet

  backend:
    build: ./server
    restart: unless-stopped
    ports:
      - 8001:5000
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/racingla?directConnection=true

  frontend:
    build:
      context: ./client
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8001
    restart: unless-stopped
    ports:
      - 8000:3000


volumes:
  data:
